### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by gauthamk97** [digaru19/NITT-SonicWall-Login#2]
I followed the instructions as per the readme, but I've been getting the following error :-

```
Reading credentials ...
 Authenticating with NITT SonicWall ...
Traceback (most recent call last):
  File "SonicWall_Login.py", line 103, in <module>
    if login(session):
  File "SonicWall_Login.py", line 63, in login
    t = session.get(base_url + 'auth1.html')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 519, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:590)
```

**Comment by digaru19** [comment]
Seems like many OS X users have faced the same issue ( [requests/issues/3006](https://github.com/requests/requests/issues/3006) ). 
Can you try installing the `ndg-httpsclient` python package.
i.e. `pip install ndg-httpsclient`
